#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2015 twxl1993 <twxl1993@gmail.com>
# 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for macvlan.
LUCI_DEPENDS:=+kmod-macvlan

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
