#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2015 twxl1993 <twxl1993@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the MWAN3 multiwan hotplug script
LUCI_DEPENDS:=+mwan3 +luci-app-firewall +luci-lib-nixio

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
